### ISSUE TITLE
Can't upload the theme

### ISSUE THREAD

**Issue by pascalandy** [mouse-reeve/teatheme#1]
<img width="962" alt="screen shot 2017-08-12 at 10 04 51 am" src="https://user-images.githubusercontent.com/6694151/29241353-bff3df5a-7f45-11e7-937b-17a70de3794c.png">

Using Ghost 1.5.2

Cheers!
Pascal

**Comment by mouse-reeve** [comment]
My bad, should be working now

**Comment by pascalandy** [comment]
Great thank you!
